[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Velocidad del monitor serial
monitor_speed = 115200

; Librería del lector RFID
lib_deps = 
	miguelbalboa/MFRC522 @ ^1.4.11

; Banderas obligatorias para ver el Serial por USB en la ESP32-S3
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1